name: ci/cd

on:
  push:
    branches:
      - "main"

jobs:
  # build:
  #    runs-on: ubuntu-latest
  #    steps:
  #      -
  #        name: Checkout
  #        uses: actions/checkout@v3
  #      -
  #        name: Login to Docker Hub
  #        uses: docker/login-action@v3
  #        with:
  #          username: ${{ secrets.DOCKERHUB_USERNAME }}
  #          password: ${{ secrets.DOCKERHUB_TOKEN }}
  #      -
  #        name: Set up Docker Buildx
  #        uses: docker/setup-buildx-action@v2
  #      -
  #        name: Build and push
  #        uses: docker/build-push-action@v4
  #        with:
  #          context: .
  #          file: ./Dockerfile
  #          push: true
  #          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mainproject:latest   
  deploy:
    # needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: appleboy/ssh-action@master
      name: Docker-Compose Remote Deployment
      with:
        host: 192.168.1.8
        port: 22
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
           ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY root@192.168.1.8 "
           cd /root/test &&
           docker compose pull &&
           docker compose up -d"

        
           # cd /root/test10 &&    
           #$SSH_PRIVATE_KEY
           # docker compose pull &&
           # docker compose up -d"
